# Generated by Django 4.2 on 2024-05-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brij', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brajbhumi',
            name='choice',
            field=models.CharField(max_length=100),
        ),
    ]
