# Generated by Django 4.2 on 2024-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brij', '0002_alter_brajbhumi_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brajbhumi',
            name='choice',
            field=models.CharField(max_length=10),
        ),
    ]
