# Generated by Django 4.2 on 2024-05-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brij', '0003_alter_brajbhumi_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='brajbhumi',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
