# Generated by Django 4.2 on 2024-05-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brij', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
